language: python
python:
  - 2.7
env:
  - PLONE=4.2
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  - mkdir -p downloads/dist
#  - wget -qnd -P downloads/dist -rl 1 http://dist.plone.org/release/$PLONE-latest/ &
install:
  - python bootstrap.py -c test-$PLONE.x.cfg
  - bin/buildout -t 5 -Nqc test-$PLONE.x.cfg
script:
  - bin/test